# Example: S3 Bucket created via ACK
apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: eks-capabilities-bucket
  namespace: default
  labels:
    Environment: example
    ManagedBy: terraform
  annotations:
    # Delete AWS resource when Kubernetes resource is deleted (default behavior)
    services.k8s.aws/deletion-policy: Delete
spec:
  name: eks-capabilities-bucket
  createBucketConfiguration:
    locationConstraint: ap-southeast-2
