apiVersion: kro.run/v1alpha1
kind: WebAppStack
metadata:
  name: eks-capabilities-app
  namespace: default
spec:
  name: eks-capabilities-app
  team: platform-team
  image: ghcr.io/platformfuzz/awsfanboy-feijoa-app-image:latest
  replicas: 2
  containerPort: 80
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/load-balancer-name: eks-capabilities-app-alb
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  bucket:
    enabled: false
    name: eks-capabilities-app-bucket
    region: ap-southeast-2
